# Generated by Django 3.2 on 2021-04-13 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='pickup_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='pickup_type',
            field=models.CharField(choices=[('1', 'In-Store'), ('2', 'Curbside')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
