# Generated by Django 3.2 on 2021-04-13 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210413_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pickup_type',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_type',
            field=models.CharField(choices=[('1', 'In-Store'), ('2', 'Curbside')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
