# Generated by Django 3.2 on 2021-04-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_type',
            field=models.CharField(choices=[('in-store', 'in-store'), ('curbside', 'curbside')], max_length=10),
        ),
    ]
