# Generated by Django 3.2 on 2021-04-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_reminderemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderemail',
            old_name='email',
            new_name='remindemail',
        ),
    ]
